baseurl: ""
url: "https://hacktival.io/"
lang: en_US
logo: /assets/images/thumbnail.jpg
title: Hacktival Hackathon
tagline: Germanys largest student-run hackathon
description: >-
  The Hacktival Hackthon is the largest student-run hackathon in Germany.
  Our goal is to bring people from different fields together to create something awesome.
author: Hack &amp; Söhne
google_site_verification: tjukQQpmzsqdbPMnXjNBcrTMyJvr9QDKjFdGEuhEJwM

# Reusable links (using YAML anchors)
facebook_link: &facebook_link https://www.facebook.com/hackundsoehne/
twitter_link: &twitter_link https://twitter.com/hackundsoehne
instagram_link: &instagram_link https://www.instagram.com/hackundsoehne/
linkedin_link: &linkedin_link https://www.linkedin.com/company/hack-&-s%C3%B6hne
github_link: &github_link https://github.com/hackundsoehne
youtube_link: &youtube_link https://www.youtube.com/channel/UCYchla3LyKoOQSdnEIl4oqQ
newsletter_link: &newsletter_link http://eepurl.com/cUkPyn
apply_link: &apply_link https://apply.hacktival.io/

# Social media SEO (read jekyll-seo-tag plugin usage)
social:
  name: Hack und Söhne
  links:
    - *facebook_link
    - *twitter_link
    - *instagram_link
    - *linkedin_link
    - *github_link
    - *youtube_link

twitter:
  username: hackundsoehne
  card: summary

# Front matter defaults
defaults:
  - scope:
      path: ""
    values:
      image:
        path: /assets/images/thumbnail.jpg
        width: 1200
        height: 628


# Sidebar main action
main_action_name: Apply now
main_action_link: *apply_link

# Jekyll collections
collections:
  - cats
  - days
  - jury

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

exclude: ["README.md"]
