baseurl: ""
url: "https://hacktival.io/"
lang: en_US
logo: /assets/images/hacktival_cover.jpg
image: /assets/images/hacktival_cover.jpg
title: Hacktival Hackathon
tagline: Germanys largest student-run hackathon
description: >-
  The Hacktival Hackthon is the largest student-run hackathon in Germany.
  Our goal is to bring people from different fields together to create something awesome.
author: Hack &amp; Söhne
google_site_verification: tjukQQpmzsqdbPMnXjNBcrTMyJvr9QDKjFdGEuhEJwM

# Reusable links (using YAML anchors)
facebook_link: &facebook_link https://www.facebook.com/hackundsoehne/
twitter_link: &twitter_link https://twitter.com/hackundsoehne
instagram_link: &instagram_link https://www.instagram.com/hackundsoehne/
linkedin_link: &linkedin_link https://www.linkedin.com/company/hack-&-s%C3%B6hne
github_link: &github_link https://github.com/hackundsoehne
youtube_link: &youtube_link https://www.youtube.com/channel/UCYchla3LyKoOQSdnEIl4oqQ
newsletter_link: &newsletter_link http://eepurl.com/cUkPyn
apply_link: &apply_link https://apply.hacktival.io/

# Social media SEO (read jekyll-seo-tag plugin usage)
social:
  name: Hack und Söhne
  links:
    - *facebook_link
    - *twitter_link
    - *instagram_link
    - *linkedin_link
    - *github_link
    - *youtube_link

twitter:
  username: hackundsoehne
  card: summary

# Sidebar main action
main_action_name: Get notified
main_action_link: *newsletter_link

# Jekyll collections
collections:
  - cats
  - days
  - jury

# Corresponds to the 'theme-colors' defined in the main.scss file.
# These colors are used to dynamically color widgets such as the tablist.
color_names:
  - violet
  - blue
  - green
  - orange
  - red
  - yellow

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

exclude: ["README.md"]
