baseurl: ""
url: "https://hacktival.io/"
lang: en_US
logo: /assets/images/hacktival_cover.jpg
image: /assets/images/hacktival_cover.jpg
title: Hacktival Hackathon
description: >-
  The Hacktival Hackthon is the largest student-run hackathon in Germany.
  Our goal is to bring people from different fields together to create something awesome.
author: Hack &amp; Söhne
google_site_verification: tjukQQpmzsqdbPMnXjNBcrTMyJvr9QDKjFdGEuhEJwM

main_action_name: Signup
main_action_link: https://apply.hacktival.io/

collections:
  - cats
  - days

# Corresponds to the 'theme-colors' defined in the main.scss file.
# These colors are used to dynamically color widgets such as the tablist.
color_names:
  - violet
  - blue
  - green
  - orange
  - red
  - yellow

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed

exclude: ["README.md"]
